### ISSUE TITLE
Set up unit tests + integration tests for TodoMVC

### ISSUE THREAD

**Issue by sleexyz** [sleexyz/typesafe-react-redux-example#3]
- Test runner: mocha
- Assertion library: chai
- Component test helper: enzyme

Negotiable requirements
- Goes through webpack, so we don't have to do weird code hacks.
- Fast, hot-reloadable, for nice TDD workflow [mocha-loader can do this](https://github.com/webpack-contrib/mocha-loader)
- CI-able

@soenkehahn would love your advice! Pain points I should watch out for?

**Comment by soenkehahn** [comment]
Sorry, didn't see this. Better come over and talk in person. :)
